# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kurai/WorkSpace/Clicker/puzzle-solver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kurai/WorkSpace/Clicker/puzzle-solver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kurai/WorkSpace/Clicker/puzzle-solver/CMakeFiles /home/kurai/WorkSpace/Clicker/puzzle-solver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kurai/WorkSpace/Clicker/puzzle-solver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named solve

# Build rule for target.
solve: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 solve
.PHONY : solve

# fast build rule for target.
solve/fast:
	$(MAKE) -f CMakeFiles/solve.dir/build.make CMakeFiles/solve.dir/build
.PHONY : solve/fast

#=============================================================================
# Target rules for targets named lectureImage

# Build rule for target.
lectureImage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lectureImage
.PHONY : lectureImage

# fast build rule for target.
lectureImage/fast:
	$(MAKE) -f CMakeFiles/lectureImage.dir/build.make CMakeFiles/lectureImage.dir/build
.PHONY : lectureImage/fast

#=============================================================================
# Target rules for targets named evaluateur

# Build rule for target.
evaluateur: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 evaluateur
.PHONY : evaluateur

# fast build rule for target.
evaluateur/fast:
	$(MAKE) -f CMakeFiles/evaluateur.dir/build.make CMakeFiles/evaluateur.dir/build
.PHONY : evaluateur/fast

eval.o: eval.cpp.o

.PHONY : eval.o

# target to build an object file
eval.cpp.o:
	$(MAKE) -f CMakeFiles/evaluateur.dir/build.make CMakeFiles/evaluateur.dir/eval.cpp.o
.PHONY : eval.cpp.o

eval.i: eval.cpp.i

.PHONY : eval.i

# target to preprocess a source file
eval.cpp.i:
	$(MAKE) -f CMakeFiles/evaluateur.dir/build.make CMakeFiles/evaluateur.dir/eval.cpp.i
.PHONY : eval.cpp.i

eval.s: eval.cpp.s

.PHONY : eval.s

# target to generate assembly for a file
eval.cpp.s:
	$(MAKE) -f CMakeFiles/evaluateur.dir/build.make CMakeFiles/evaluateur.dir/eval.cpp.s
.PHONY : eval.cpp.s

inputReader.o: inputReader.cpp.o

.PHONY : inputReader.o

# target to build an object file
inputReader.cpp.o:
	$(MAKE) -f CMakeFiles/lectureImage.dir/build.make CMakeFiles/lectureImage.dir/inputReader.cpp.o
	$(MAKE) -f CMakeFiles/evaluateur.dir/build.make CMakeFiles/evaluateur.dir/inputReader.cpp.o
.PHONY : inputReader.cpp.o

inputReader.i: inputReader.cpp.i

.PHONY : inputReader.i

# target to preprocess a source file
inputReader.cpp.i:
	$(MAKE) -f CMakeFiles/lectureImage.dir/build.make CMakeFiles/lectureImage.dir/inputReader.cpp.i
	$(MAKE) -f CMakeFiles/evaluateur.dir/build.make CMakeFiles/evaluateur.dir/inputReader.cpp.i
.PHONY : inputReader.cpp.i

inputReader.s: inputReader.cpp.s

.PHONY : inputReader.s

# target to generate assembly for a file
inputReader.cpp.s:
	$(MAKE) -f CMakeFiles/lectureImage.dir/build.make CMakeFiles/lectureImage.dir/inputReader.cpp.s
	$(MAKE) -f CMakeFiles/evaluateur.dir/build.make CMakeFiles/evaluateur.dir/inputReader.cpp.s
.PHONY : inputReader.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/lectureImage.dir/build.make CMakeFiles/lectureImage.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/lectureImage.dir/build.make CMakeFiles/lectureImage.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/lectureImage.dir/build.make CMakeFiles/lectureImage.dir/main.cpp.s
.PHONY : main.cpp.s

solve.o: solve.cpp.o

.PHONY : solve.o

# target to build an object file
solve.cpp.o:
	$(MAKE) -f CMakeFiles/solve.dir/build.make CMakeFiles/solve.dir/solve.cpp.o
.PHONY : solve.cpp.o

solve.i: solve.cpp.i

.PHONY : solve.i

# target to preprocess a source file
solve.cpp.i:
	$(MAKE) -f CMakeFiles/solve.dir/build.make CMakeFiles/solve.dir/solve.cpp.i
.PHONY : solve.cpp.i

solve.s: solve.cpp.s

.PHONY : solve.s

# target to generate assembly for a file
solve.cpp.s:
	$(MAKE) -f CMakeFiles/solve.dir/build.make CMakeFiles/solve.dir/solve.cpp.s
.PHONY : solve.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... solve"
	@echo "... lectureImage"
	@echo "... evaluateur"
	@echo "... eval.o"
	@echo "... eval.i"
	@echo "... eval.s"
	@echo "... inputReader.o"
	@echo "... inputReader.i"
	@echo "... inputReader.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... solve.o"
	@echo "... solve.i"
	@echo "... solve.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

